### ISSUE TITLE
Comments posted to different message than commented on

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#236]
This is a weird one. When I sometimes post a comment on update/detail, it sometimes doesn't show as comment on the message. So I rewrite the comment and post again and it does show on the message. However, after I view the updates I see the comment I posted first appear as a comment on a different message than the one I posted it to.

Issue seen on Chrome by several users. See these screenshots for the results (comment by me accentuated).

<img width="1440" alt="screen shot 2016-02-04 at 11 29 40" src="https://cloud.githubusercontent.com/assets/14044235/12812510/a3b2d364-cb32-11e5-9ed3-312be54e1102.png">
<img width="1440" alt="screen shot 2016-02-04 at 11 29 56" src="https://cloud.githubusercontent.com/assets/14044235/12812511/a3b50080-cb32-11e5-93fa-f89f752383e5.png">

**Comment by andreleon** [comment]
@ralphboeije I'm sorry, but I really need steps to reproduce this issue.

**Comment by ralphboeije** [comment]
@andreleon Steps will follow shortly. It now seems that it happens when hitting backspace. that is also the issue with #228

**Comment by andreleon** [comment]
@ralphboeije issue #228 has been fixed in branch fix-motivation-comment, maybe that will also fix this issue. I've already created a pull-request

**Comment by ralphboeije** [comment]
@andreleon I have now reproduced it several times with these steps:
1. Click a notification
2. Click another notification within the same part-up
3. Post a comment on this update
4. See the loader spinner on the orange post button
5. See that the comment is not shown after the loader spinner stops
6. View all updates and see that your comment is posted to update you first viewed from the notifications

I don't know if your PR also fixes this?

**Comment by andreleon** [comment]
@ralphboeije thanks for these steps, they really helped me in fixing this issue. I've created a pull-request that fixes the problem.

**Comment by ralphboeije** [comment]
@andreleon in acceptance this doesn't fix the issue. See the steps and screenshot below.

To reproduce:
1. Go to pu-acceptance.lifely.nl and log in (admin or regular user account)
2. Make sure you have two notifications of an update in the same part-up
3. Click the first notification and post a comment --> see the comment is posted
4. Click the second notification and try to post a comment
5. See the spinner on the post button keep spinning and the comment not posted
6. NB: even if you click other notifications the comment is persisted below the other update!!

<img width="1440" alt="screen shot 2016-02-12 at 10 42 21" src="https://cloud.githubusercontent.com/assets/14044235/13003503/30fc0954-d176-11e5-9bcd-aa36b0900f75.png">
<img width="1440" alt="screen shot 2016-02-12 at 10 42 36" src="https://cloud.githubusercontent.com/assets/14044235/13003504/30fe1906-d176-11e5-8c2d-9cb330ebabd8.png">

**Comment by peterpeerdeman** [comment]
was fixed in 0c87a026849dc0871011ea674874a88d45c1d618
